server:
  port: ${PORT:0}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3307/productdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Turkey
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  app-details: qprhttps://github.com/abhinandanchivate/springbootconfigicici.git

  eureka:  
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
